// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	aws "github.com/aws/aws-sdk-go-v2/aws"
)

func AnyAwsEndpoint() aws.Endpoint {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(aws.Endpoint))(nil)).Elem()))
	var nullValue aws.Endpoint
	return nullValue
}

func EqAwsEndpoint(value aws.Endpoint) aws.Endpoint {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue aws.Endpoint
	return nullValue
}
